lilianews/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
	path("", views.listar_noticias, name="listar_noticias"),
	path("<int:id_noticia>/", views.ver_noticia, name="ver_noticia")
	]

lilianews/lilianews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/",include("blog.urls"))
]

lilianews/blog/models.py
from django.db import models

class Noticia(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.CharField(max_length=1000)
	fecha_pub = models.DateTimeField(auto_now_add =True)

	def __str__(self):
		return "%s %s" % (self.titulo,self.fecha_pub)			

lilianews/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse


#MTV
#Model
#View
#Template
#Importacion de librerias Personales 
from . import models


def listar_noticias(request):
	"""
		obtiene las noticias de la base de datos 

		Retorna:
			El Listado de las noticias 
	"""
	#Obtiene el listado de todas las noticias
	#de la base de datos y la asigna a la variable 
	#noticias
	noticias = models.Noticia.objects.all()

	#Retorna todo renderizado para ser leido en el
	#explorador, tiene tres parametros
	#Solicitud(resquest), plantilla de datos y datos 
	return render(
					request, 
					"./noticias/index.html",
					 {"news":noticias}
					 )


def ver_noticia(request, id_noticia):
	"""
		Obtiene una noticia de la base de datos 

		Parametros:
			id_noiticia es numerico y hace referencia 
			al identificador denla noticia buscada
		
		Retorna 
			la noticia buscada si existe 	
	"""		

	noticia = models.Noticia.objects.get(id=id_noticia)

	return render(
					request,
					"./noticias/detalle.html",
					{"noticia":noticia}

				)

lilianews/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block titulo %}Noticias{% endblock %}
	</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body class="bg-info">
	<div id="header" class="bg-info py-4" style="background-image: url(https://i.pinimg.com/736x/27/58/b0/2758b004c8e3cc3fcd5fcb740810e2f8.jpg);">
		<!--
			h1 (h = header) es igual a encabezado uno
			display mostrar = tamaño
		-->
			
		<a href="{% url 'blog:listar_noticias' %}" class="
		text-white">
			<h1 class="display-3 text-center">
				Lilia <b><i>News</i></b></h1>
			</a>	
	
		</div>
	<div class="container border border-danger bg-white" id="principal">
		{% block informacion %}

		{% endblock %}	
	</div>
	<footer id="sticky-footer" class="py-4 bg-info text-body-50">
		<div class= "container text-center">
			<small>
				Todos los Derechos Reservados &copy; Lilia News
			</small>
		</div>
	</footer>	
</body>
</html>

lilianews/blog/templates/noticias/detalle.html
<!-- Extiende la configuracion y maquetacion de la pagina base 
-->
{% extends 'base.html' %}	


{% block titulo %}
	{{ noticia.titulo }}
{% endblock %}	
<!--
	pasa la informacion que va ser mostrada en el bloque 
	informacion de la pagina base.html
-->	
{% block informacion %}

	<h1>{{ noticia.titulo}}</h1>

	<p>{{noticia.descripcion}}</p>	
	<div class='text-info'>
		Fecha de publicacion: {{ noticia.fecha_pub  }}
	</div>
{% endblock %}	

lilianews/blog/templates/noticias/index.html
<!-- Extiende la configuracion y maquetacion de la pagina base
 -->
{% extends 'base.html' %}	

<!--
	pasa la informacion que va ser mostrada en el bloque 
	informacion de la pagina base.html
-->	
{% block informacion %}		
	{% for new in news %}
		<div class="p-1">
			<h2 class="text-info">
				<a href="{% url 'blog:ver_noticia' new.id %}">
				     {{ new.titulo }}
				</a>
			</h2>
			<p> 
				{{ new.descripcion }}
				<a href="{% url 'blog:ver_noticia' new.id %}">
				     Ver...
				</a>
			</p>
			<hr>
		</div>	
	{% endfor %}	
{% endblock %}	